project_name: ae
folders:
    - dir: /users
      storage:
        type: s3_storage
        bucket: test-mindia-bucket
      policies: []
    - dir: /users/company
      storage:
        type: s3_storage
        bucket: test-mindia-bucket
      policies: []
    - dir: /houses
      storage:
        type: filesystem_storage
        mount_dir: ./data
      policies: []
    - dir: /houses/garden
      storage:
        type: filesystem_storage
        mount_dir: ./data
      policies: []
api_server:
    port: 3500
