name: ae
api_server:
    api_server: 3500
folders:
    - dir: /houses
      storage:
        type: filesystem
        mount_dir: ./data
      backup:
        type: filesystem
        mount_dir: ./data/backup
      automations:
        - automationconfig:
            steps:
                - children: []
                - children:
                    - automationconfig:
                        steps:
                            - children: []
                              suffix: xl
                            - children: []
                              size:
                                width: 300
                                height: 300
                    - automationconfig:
                        steps:
                            - children: []
                              suffix: md
                            - children: []
                              size:
                                width: 200
                                height: 200
    - dir: /houses/garden
      storage:
        type: filesystem
        mount_dir: ./data
      automations:
        - automationconfig:
            steps:
                - children: []
                - children:
                    - automationconfig:
                        steps:
                            - children: []
                              suffix: xl
                            - children: []
                              size:
                                width: 300
                                height: 300
                    - automationconfig:
                        steps:
                            - children: []
                              suffix: md
                            - children: []
                              size:
                                width: 200
                                height: 200
    - dir: /users
      storage:
        type: s3
      backup:
        type: s3
      automations:
        - automationconfig:
            steps:
                - children: []
                - children:
                    - automationconfig:
                        steps:
                            - children: []
                              suffix: xl
                            - children: []
                              size:
                                width: 300
                                height: 300
                    - automationconfig:
                        steps:
                            - children: []
                              suffix: md
                            - children: []
                              size:
                                width: 200
                                height: 200
    - dir: /users/company
      storage:
        type: s3
      automations:
        - automationconfig:
            steps:
                - children: []
                - children:
                    - automationconfig:
                        steps:
                            - children: []
                              suffix: xl
                            - children: []
                              size:
                                width: 300
                                height: 300
                    - automationconfig:
                        steps:
                            - children: []
                              suffix: md
                            - children: []
                              size:
                                width: 200
                                height: 200
