name: ae
api_server:
    api_server: 3500
folders:
    - dir: /houses
      storage:
        type: filesystem
        mount_dir: ./data
      backup:
        type: filesystem
        mount_dir: ./data/backup
      automations:
        - automation:
            automationconfig:
                namer: {}
                steps:
                    - automationstep:
                        children:
                            - automationconfig:
                                namer:
                                    suffix: xl
                                steps:
                                    - automationstep:
                                        children: []
                                      size:
                                        width: 250
                                        height: 250
                            - automationconfig:
                                namer:
                                    suffix: md
                                steps:
                                    - automationstep:
                                        children: []
                                      size:
                                        width: 150
                                        height: 150
                      children:
                        - automationconfig:
                            namer:
                                suffix: xl
                            steps:
                                - automationstep:
                                    children: []
                                  size:
                                    width: 250
                                    height: 250
                        - automationconfig:
                            namer:
                                suffix: md
                            steps:
                                - automationstep:
                                    children: []
                                  size:
                                    width: 150
                                    height: 150
          applytocurrentfiles: true
      policies:
        - policyconfig:
            content_types_allowed:
                - image/jpeg
            content_length_max: 10000000
    - dir: /houses/garden
      storage:
        type: filesystem
        mount_dir: ./data
      automations:
        - automation:
            automationconfig:
                namer: {}
                steps:
                    - automationstep:
                        children:
                            - automationconfig:
                                namer:
                                    suffix: xl
                                steps:
                                    - automationstep:
                                        children: []
                                      size:
                                        width: 250
                                        height: 250
                            - automationconfig:
                                namer:
                                    suffix: md
                                steps:
                                    - automationstep:
                                        children: []
                                      size:
                                        width: 150
                                        height: 150
                      children:
                        - automationconfig:
                            namer:
                                suffix: xl
                            steps:
                                - automationstep:
                                    children: []
                                  size:
                                    width: 250
                                    height: 250
                        - automationconfig:
                            namer:
                                suffix: md
                            steps:
                                - automationstep:
                                    children: []
                                  size:
                                    width: 150
                                    height: 150
          applytocurrentfiles: true
      policies: []
    - dir: /users
      storage:
        type: s3
      backup:
        type: s3
      automations:
        - automation:
            automationconfig:
                namer: {}
                steps:
                    - automationstep:
                        children:
                            - automationconfig:
                                namer:
                                    suffix: xl
                                steps:
                                    - automationstep:
                                        children: []
                                      size:
                                        width: 250
                                        height: 250
                            - automationconfig:
                                namer:
                                    suffix: md
                                steps:
                                    - automationstep:
                                        children: []
                                      size:
                                        width: 150
                                        height: 150
                      children:
                        - automationconfig:
                            namer:
                                suffix: xl
                            steps:
                                - automationstep:
                                    children: []
                                  size:
                                    width: 250
                                    height: 250
                        - automationconfig:
                            namer:
                                suffix: md
                            steps:
                                - automationstep:
                                    children: []
                                  size:
                                    width: 150
                                    height: 150
          applytocurrentfiles: true
      policies: []
    - dir: /users/company
      storage:
        type: s3
      automations:
        - automation:
            automationconfig:
                namer: {}
                steps:
                    - automationstep:
                        children:
                            - automationconfig:
                                namer:
                                    suffix: xl
                                steps:
                                    - automationstep:
                                        children: []
                                      size:
                                        width: 250
                                        height: 250
                            - automationconfig:
                                namer:
                                    suffix: md
                                steps:
                                    - automationstep:
                                        children: []
                                      size:
                                        width: 150
                                        height: 150
                      children:
                        - automationconfig:
                            namer:
                                suffix: xl
                            steps:
                                - automationstep:
                                    children: []
                                  size:
                                    width: 250
                                    height: 250
                        - automationconfig:
                            namer:
                                suffix: md
                            steps:
                                - automationstep:
                                    children: []
                                  size:
                                    width: 150
                                    height: 150
          applytocurrentfiles: true
      policies: []
