name: ae
api_server:
    api_server: 3500
folders:
    /houses:
        dir: /houses
        storage:
            mount_dir: ./data
        automations:
            - name: automation1
              steps:
                - suffix: xl
                - size:
                    width: 200
                    height: 200
            - name: automation2
              steps:
                - suffix: md
                - size:
                    width: 100
                    height: 100
    /houses/garden:
        dir: /houses/garden
        storage:
            mount_dir: ./data
        automations:
            - name: automation1
              steps:
                - suffix: xl
                - size:
                    width: 200
                    height: 200
    /users:
        dir: /users
        storage: {}
        automations: []
    /users/company:
        dir: /users/company
        storage: {}
        automations: []
