//! Build script: generates API version constants from API_VERSION env (default: v0).
//! Emits API_VERSION_STR for use in api_path! macro via env!("API_VERSION_STR").

fn main() {
    let api_version = std::env::var("API_VERSION").unwrap_or_else(|_| "v0".to_string());
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR set by cargo");
    let api_prefix = format!("/api/{}", api_version);

    let contents = format!(
        r#"// Generated by build.rs - do not edit. Version from API_VERSION env (default: v0).
pub const API_VERSION: &str = "{api_version}";
pub const API_PREFIX: &str = "{api_prefix}";
pub const API_IMAGES_PREFIX: &str = "{api_prefix}/images";
pub const API_VIDEOS_PREFIX: &str = "{api_prefix}/videos";
pub const API_DOCUMENTS_PREFIX: &str = "{api_prefix}/documents";
pub const API_AUDIOS_PREFIX: &str = "{api_prefix}/audios";
pub const API_FOLDERS_PREFIX: &str = "{api_prefix}/folders";
pub const API_ANALYTICS_PREFIX: &str = "{api_prefix}/analytics";
pub const API_AUDIT_LOGS_PREFIX: &str = "{api_prefix}/audit-logs";
pub const API_SEARCH_PREFIX: &str = "{api_prefix}/search";
pub const API_CONFIG_PREFIX: &str = "{api_prefix}/config";
pub const API_MEDIA_PREFIX: &str = "{api_prefix}/media";
pub const API_TASKS_PREFIX: &str = "{api_prefix}/tasks";
pub const API_GROUPS_PREFIX: &str = "{api_prefix}/groups";
pub const API_WEBHOOKS_PREFIX: &str = "{api_prefix}/webhooks";
pub const API_PLUGINS_PREFIX: &str = "{api_prefix}/plugins";
pub const API_UPLOADS_PREFIX: &str = "{api_prefix}/uploads";
pub const API_AUTH_PREFIX: &str = "{api_prefix}/auth";
pub const API_API_KEYS_PREFIX: &str = "{api_prefix}/api-keys";
"#,
        api_version = api_version,
        api_prefix = api_prefix,
    );

    std::fs::write(
        std::path::Path::new(&out_dir).join("api_version.rs"),
        contents,
    )
    .expect("write api_version.rs");

    // For api_path! macro: concat!("/api/", env!("API_VERSION_STR"), $path)
    println!("cargo:rustc-env=API_VERSION_STR={}", api_version);
    println!("cargo:rerun-if-env-changed=API_VERSION");
}
